"""initial schema

Revision ID: fcd1db5fa1c9
Revises: 
Create Date: 2026-06-10 11:25:17.431980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd1db5fa1c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('battery_pct', sa.Float(), nullable=False),
    sa.Column('speed_mps', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_codes', sa.JSON(), nullable=False),
    sa.Column('zone_entered', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_events_vehicle_id'), 'telemetry_events', ['vehicle_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('current_status', sa.String(), nullable=False),
    sa.Column('current_battery', sa.Float(), nullable=False),
    sa.Column('latest_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('zones',
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anomaly_type', sa.String(), nullable=False),
    sa.Column('raw_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['raw_event_id'], ['telemetry_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_timestamp'), 'anomalies', ['timestamp'], unique=False)
    op.create_index(op.f('ix_anomalies_vehicle_id'), 'anomalies', ['vehicle_id'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_vehicle_id'), 'maintenance_records', ['vehicle_id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_vehicle_id'), 'missions', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_missions_vehicle_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_maintenance_records_vehicle_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_anomalies_vehicle_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_timestamp'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_table('zones')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_telemetry_events_vehicle_id'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    # ### end Alembic commands ###
